-- Dee B2B — data export from Supabase (gsojazybzodouvdmqkvg), snapshot 2026-07-02.
-- Run after schema.sql. This is a ONE-TIME snapshot — re-export and re-run
-- immediately before the final DNS cutover (see migration plan, step 7) to
-- pick up anything written to the live Supabase-backed site in the meantime.

-- ═══════════════════════════════════════════
-- USERS (from auth.users — bcrypt hashes preserved as-is, no reset needed)
-- hello@project-1804.com promoted to admin per migration plan decision.
-- ═══════════════════════════════════════════

insert into users (id, email, password_hash, company, role, created_at) values
  ('221a5cc9-e8a4-472a-9fe2-d3ae0fc3db4f', 'hello@project-1804.com', '$2a$10$tx8.QBogEgV4JmfUOyFU4Ow8SIY32E3CQ9iDJck1uuQ1ecHPOyIFy', 'PROJECT 1804', 'admin', '2026-03-27T08:55:39.09192+00'),
  ('58b30c39-9862-43bd-aab8-024db81e4204', 'nastasiprivalova@gmail.com', '$2a$10$8mLlu9LxmCxxntSxiG9aEe.JFKutaNNRP8BeSDUbgSOG3WEItsodq', 'Eaudemoi', 'buyer', '2026-03-27T09:48:59.192965+00'),
  ('f96bc40a-0261-4838-8df9-14b15fc97be9', 'da@deeapril.com', '$2a$10$Z2Yuuyi7JcECvWKIOMZk3ucalvUsoGHN0i.AFpKrJjIxYh/z5uh0C', 'DA DESIGN', 'buyer', '2026-03-27T16:53:28.226801+00');

-- ═══════════════════════════════════════════
-- BUYER PROFILES
-- ═══════════════════════════════════════════

insert into buyer_profiles (id, user_id, company, contact, address, city, country, zip, vat, email, created_at, updated_at) values
  ('176ae525-6e47-4aba-9101-2dcc3f2b0ac9', '58b30c39-9862-43bd-aab8-024db81e4204', 'Eaudemoi', 'Anastasia ', 'Belgrade', 'Belgrade', 'Serbia', '30000', 'DK12345678', 'nastasiprivalova@gmail.com', '2026-03-27T09:48:59.578276+00', '2026-03-27T09:51:33.325+00'),
  ('ef782afe-58e6-44ee-aef6-774ec4ed0c80', 'f96bc40a-0261-4838-8df9-14b15fc97be9', 'DA DESIGN', 'DORTE DEE APRIL', 'Piniehøj 17', 'Rungsted', 'Danmark', '2960', '45305481', 'da@deeapril.com', '2026-03-27T16:53:29.049016+00', '2026-03-27T17:04:58.007+00'),
  ('b732d4a3-891f-4c13-a8ab-16a60dad9725', '221a5cc9-e8a4-472a-9fe2-d3ae0fc3db4f', 'PROJECT 1804', 'Vladimir Nikandrov', '32 Rue Saint Paul', 'Paris', 'France', '75004', 'FR12345676543', 'hello@project-1804.com', '2026-03-27T08:55:39.580193+00', '2026-04-24T17:51:47.994+00');

-- ═══════════════════════════════════════════
-- INVENTORY (22 SKUs)
-- ═══════════════════════════════════════════

insert into inventory (sku, product_name, size, stock, updated_at) values
  ('DEP100100', 'Parfum', '50 ML', 42, '2026-04-05T15:45:14.135428+00'),
  ('DEP100101', 'Parfum I', '50 ML', 20, '2026-04-05T15:45:14.135428+00'),
  ('DEP100102', 'Parfum II', '50 ML', 451, '2026-04-05T15:45:14.135428+00'),
  ('DEP100200', 'Parfum', '100 ML', 96, '2026-04-05T15:45:14.135428+00'),
  ('DEP100201', 'Parfum I', '100 ML', 30, '2026-04-05T15:45:14.135428+00'),
  ('DEP100202', 'Parfum II', '100 ML', 3454, '2026-04-05T15:45:14.135428+00'),
  ('DEP100300', 'Parfum', '20 ML', 64, '2026-04-05T15:45:14.135428+00'),
  ('DEP100301', 'Parfum I', '20 ML', 30, '2026-04-05T15:45:14.135428+00'),
  ('DEP100302', 'Parfum II', '20 ML', 54, '2026-04-05T15:45:14.135428+00'),
  ('DEP100701', 'Parfum', '2 ML', 443, '2026-04-05T15:45:14.135428+00'),
  ('DEP100702', 'Parfum I', '2 ML', 4, '2026-04-05T15:45:14.135428+00'),
  ('DEP100703', 'Parfum II', '2 ML', 53, '2026-04-05T15:45:14.135428+00'),
  ('DEP100800', 'Discovery Kit', 'KIT', 94, '2026-04-05T15:45:14.135428+00'),
  ('TEST100100', 'Tester / Parfum', '50 ML', 45, '2026-04-05T15:45:14.135428+00'),
  ('TEST100101', 'Tester / Parfum I', '50 ML', 43, '2026-04-05T15:45:14.135428+00'),
  ('TEST100102', 'Tester / Parfum II', '50 ML', 540, '2026-04-05T15:45:14.135428+00'),
  ('TEST100200', 'Tester / Parfum', '100 ML', 54, '2026-04-05T15:45:14.135428+00'),
  ('TEST100201', 'Tester / Parfum I', '100 ML', 450, '2026-04-05T15:45:14.135428+00'),
  ('TEST100202', 'Tester / Parfum II', '100 ML', 45, '2026-04-05T15:45:14.135428+00'),
  ('TEST100300', 'Tester / Parfum', '20 ML', 54, '2026-04-05T15:45:14.135428+00'),
  ('TEST100301', 'Tester / Parfum I', '20 ML', 45, '2026-04-05T15:45:14.135428+00'),
  ('TEST100302', 'Tester / Parfum II', '20 ML', 54, '2026-04-05T15:45:14.135428+00');

-- ═══════════════════════════════════════════
-- PROMO CODES
-- ═══════════════════════════════════════════

insert into promo_codes (id, code, label, discount_type, prices, created_at) values
  ('d692b266-464c-4cf4-81ab-5a75cabdee58', 'MOODSCENTBAR', 'B2VIP', 'fixed_prices', '{"KIT":8,"2 ML":2,"20 ML":16,"50 ML":35,"100 ML":48}', '2026-04-03T15:32:40.658997+00');

-- ═══════════════════════════════════════════
-- ORDERS (both placed by hello@project-1804.com — test orders, no real customer data)
-- Note: id is normally auto-generated by next_order_id(); explicit values here
-- preserve the historical IDs from Supabase so existing references (emails
-- already sent, deep links) keep working after migration.
-- ═══════════════════════════════════════════

insert into orders (id, user_id, buyer_company, buyer_contact, buyer_address, buyer_city, buyer_country, buyer_zip, buyer_vat, buyer_email, lines, total_wsp, vat_rate, vat_label, vat_note, vat_amount, shipping_amount, total_with_vat, deposit_amount, balance_amount, status_deposit_invoiced, status_deposit_paid, status_packed, status_balance_invoiced, status_balance_paid, status_shipped, status_received, cancelled, promo_code, promo_label, created_at) values
  ('DA-2604-9017', '221a5cc9-e8a4-472a-9fe2-d3ae0fc3db4f', 'PROJECT 1804', 'Vladimir Nikandrov', '32 Rue Saint Paul', 'Paris', 'France', '75004', 'FR12345676543', 'hello@project-1804.com',
   '[{"ean":"0788364060525","qty":4,"sku":"DEP100200","size":"100 ML","total":300,"product":"Parfum","unitPrice":75},{"ean":"0792649468432","qty":3,"sku":"DEP100100","size":"50 ML","total":165,"product":"Parfum","unitPrice":55},{"ean":"0788364060594","qty":2,"sku":"DEP100300","size":"20 ML","total":50,"product":"Parfum","unitPrice":25},{"ean":null,"qty":2,"sku":"DEP100701","size":"2 ML","total":4,"product":"Parfum","unitPrice":2},{"ean":"0788364060532","qty":2,"sku":"DEP100201","size":"100 ML","total":150,"product":"Parfum I","unitPrice":75},{"ean":"0788364060501","qty":2,"sku":"DEP100101","size":"50 ML","total":110,"product":"Parfum I","unitPrice":55},{"ean":"0788364060563","qty":2,"sku":"DEP100301","size":"20 ML","total":50,"product":"Parfum I","unitPrice":25},{"ean":"0788364060518","qty":2,"sku":"DEP100102","size":"50 ML","total":110,"product":"Parfum II","unitPrice":55},{"ean":null,"qty":2,"sku":"TEST100101","size":"50 ML","total":90,"product":"Tester / Parfum I","unitPrice":45},{"ean":null,"qty":6,"sku":"DEP100800","size":"KIT","total":48,"product":"Discovery Kit","unitPrice":8}]'::jsonb,
   1077, 0, 'EU Reverse Charge', 'VAT 0% — Reverse charge, Art. 196 Council Directive 2006/112/EC', 0, 35, 1112, 323.1, 753.9,
   true, true, true, true, true, true, true, false, null, null, '2026-04-24T17:19:53.813033+00'),
  ('DA-2604-1825', '221a5cc9-e8a4-472a-9fe2-d3ae0fc3db4f', 'PROJECT 1804', 'Vladimir Nikandrov', '32 Rue Saint Paul', 'Paris', 'France', '75004', 'FR12345676543', 'hello@project-1804.com',
   '[{"ean":"0792649468432","qty":5,"sku":"DEP100100","size":"50 ML","total":275,"product":"Parfum","unitPrice":55},{"ean":"0788364060594","qty":4,"sku":"DEP100300","size":"20 ML","total":100,"product":"Parfum","unitPrice":25}]'::jsonb,
   375, 0, 'EU Reverse Charge', 'VAT 0% — Reverse charge, Art. 196 Council Directive 2006/112/EC', 0, 35, 410, 112.5, 262.5,
   true, false, false, false, false, false, false, false, null, null, '2026-04-24T17:50:28.094203+00');

-- ═══════════════════════════════════════════
-- ORDER NOTES
-- ═══════════════════════════════════════════

insert into order_notes (id, order_id, text, author, is_admin, created_at) values
  ('9a56e747-a362-4309-9ccd-622b318259b0', 'DA-2604-9017', 'Hey! Test', 'Admin', true, '2026-04-24T17:21:45.833023+00');
